 * Serving Flask app "map4_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "map4_service.py", line 105, in <module>
    app.run(host='0.0.0.0',debug = True)
  File "/home/ml.user/QA/Sayan/nirikshmika/code/venv/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ml.user/QA/Sayan/nirikshmika/code/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 988, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "map4_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 288-373-258
